# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5785d4e6a946e105c4968340cd3da0f3e3b255450b4544ea6e13aad9d6fbdf736a4bf92470cbe77d2d8b3fd92432007fc28404c1a24ca69911b9b561b22d1fe6

test:
  secret_key_base: 410dce54ecda017db1104ec84912931b7018e44e510fae8f1b8a0d0561817ea0daf4131498ddfb0051f65c2fe805419a43c4e0ef4ec28d3ae77b5f791e358e38

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
